# encoding: utf-8

truncate_table "misc_feed_histories"
truncate_table "misc_feed_items"
truncate_table "misc_inquiries"
truncate_table "misc_portal_photos"
truncate_table "misc_portal_recommends"
truncate_table "misc_portal_links"
truncate_table "misc_search_columns"
truncate_table "misc_search_selects"
truncate_table "misc_social_update_photos"
truncate_table "misc_social_updates"
truncate_table "misc_tweets"

reset_sequence "misc_feed_histories_id_seq"
reset_sequence "misc_feed_items_id_seq"
reset_sequence "misc_inquiries_id_seq"
reset_sequence "misc_portal_photos_id_seq"
reset_sequence "misc_portal_recommends_id_seq"
reset_sequence "misc_portal_links_id_seq"
reset_sequence "misc_search_columns_id_seq"
reset_sequence "misc_search_selects_id_seq"
reset_sequence "misc_social_update_photos_id_seq"
reset_sequence "misc_social_updates_id_seq"
reset_sequence "misc_tweets_id_seq"